name: Test
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    name: ${{ matrix.module }} ${{ matrix.os }} deno-${{ matrix.deno }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        module: [ansi, command, flags, keycode, keypress, prompt, table, testing]
        os: [macOS-latest, windows-latest, ubuntu-latest]
        deno: [v1.x]
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Test ${{ matrix.module }}
        run: deno task coverage:${{ matrix.module }}

      - name: Upload ${{ matrix.module }} coverage
        uses: codecov/codecov-action@v3
        with:
          name: ${{ matrix.module }}-${{ matrix.os }}-${{ matrix.deno }}
          files: dist/coverage/${{ matrix.module }}/cov.lcov
          flags: ${{ matrix.module }}
